name: main

# run on pull requests and pushes to main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: 📦 Install Dependencies
        run: npm ci

      - name: ✨ Check Format
        run: npm run format:check

      - name: 🧹 Lint
        run: npm run lint

      - name: 👷 Build website
        run: npm run build
      # push to github pages
      - name: 📦 Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build
      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
        if: ${{ github.ref == 'refs/heads/main' }}

  # deploy to github pages
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: 📚 Git Checkout
#        uses: actions/checkout@v2
#        with:
#          persist-credentials: false
#          fetch-depth: 0
#
#      - name: ⚙️ Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.x
#          cache: npm
#          cache-dependency-path: package-lock.json
#
#      - name: 📦 Install Dependencies
#        run: npm ci
#
#      - name: 📦 Download build output
#        uses: actions/download-artifact@v2
#        with:
#          name: build
#      - name: 🚀 Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./build
#          publish_branch: gh-pages
#        if: ${{ github.ref == 'refs/heads/main' }}
